version: '3'
services:

  redis:
    image: redis:latest
    restart: always

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - app

volumes:
  static_value:
  media_value:

