version: '3.9'
services:

  db:
    container_name: esmo_db
    image: postgres:14-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    container_name: esmo_redis
    image: redis:latest
    restart: always

  app:
    container_name: esmo_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
    command: gunicorn application.wsgi:application --bind 0.0.0.0:8000

  nginx:
    container_name: esmo_nginx
    image: nginx:latest
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - app

volumes:
  static_value:
  media_value:
  postgres_data:
